import fs from 'node:fs';
import fsp from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import process from 'node:process';
import crypto from 'node:crypto';
import { spawn } from 'node:child_process';
import { inflateRawSync } from 'node:zlib';

const repoRoot=path.resolve(import.meta.dirname,'..'),artifactRoot=path.join(repoRoot,'artifacts'),evidenceRoot=path.join(repoRoot,'evidence');
const attachments={
  '输入数据包.zip':'f84bb18d8fd8a83fbf81a2c072ff79226987300a53b3546d72bb3e6447d80fcf',
  'reference.zip':'dbed9f4913218d65d878ad38f67ebde72312a34cb6afd344492225d14fbd797c',
  '关键标准答案.xlsx':'6194b7c6b83b86872d8a74bba8402e1d09fabc4a09093b6735290d33a2fae2b5',
  '任务规格转化.xlsx':'5ecc9b91691e93a2334fd01e761abac64b9e9555913425d671e8c2fca13cdc8a'
};
const taskHashes={
  '任务名称.txt':'a3028e04f87dd52316a2154e4fba38d3a3567e03ded8dd49d57b1cfa8a4f3868',
  '任务概要.txt':'44ae98dab63ca691705aae1b535495e4e1f1f92b10a3bd7af03d02c1e9031e3a',
  '任务prompt.txt':'4d1b559f77b40d8bad82e64dc73305d4c1f1fdf603e5fd0a5f6e05eec3180b97',
  '关键动作.txt':'d5497ad1e9da1867ff86b24004ce4444635ea44cd5a2a93f8dd1d226439ac64d',
  '评分表.txt':'5b7e46f273e64889b8d065b5303610ccd15dfdb692ba9a4a658c13fe7b34e310',
  '环境依赖.txt':'eb7ca0143f2386f792181aac71721ce0f322bba62791416e88eb4143faebf5fb',
  '相关专业软件的关键步骤.txt':'cd6d4698ca64e1522a356ac0233034813d66c5ba5b51e867e9713725d7a88c18'
};
const deliveryMembers=['output/check_api_compat.mjs','output/reports/breaking_changes.csv','output/reports/deprecation_windows.csv','output/reports/release_advisory.json','output/reports/report_consistency.json','output/reports/sdk_impact_matrix.csv'];
const sha=body=>crypto.createHash('sha256').update(body).digest('hex'),shaFile=file=>sha(fs.readFileSync(file)),assert=(value,message)=>{if(!value)throw new Error(message);};
function parseZipBytes(data){const files=new Map();let offset=0;while(offset+46<=data.length){if(data.readUInt32LE(offset)!==0x02014b50){offset+=1;continue;}const method=data.readUInt16LE(offset+10),compressedSize=data.readUInt32LE(offset+20),uncompressedSize=data.readUInt32LE(offset+24),nameLength=data.readUInt16LE(offset+28),extraLength=data.readUInt16LE(offset+30),commentLength=data.readUInt16LE(offset+32),localOffset=data.readUInt32LE(offset+42),name=data.subarray(offset+46,offset+46+nameLength).toString('utf8').replaceAll('\\','/');if(!name.endsWith('/')){const localNameLength=data.readUInt16LE(localOffset+26),localExtraLength=data.readUInt16LE(localOffset+28),start=localOffset+30+localNameLength+localExtraLength,compressed=data.subarray(start,start+compressedSize),body=method===0?compressed:method===8?inflateRawSync(compressed):null;assert(body&&body.length===uncompressedSize,'ZIP extraction error');files.set(name,body);}offset+=46+nameLength+extraLength+commentLength;}return files;}
const parseZip=file=>parseZipBytes(fs.readFileSync(file));
async function extract(file,destination){for(const[name,bytes]of parseZip(file)){const target=path.resolve(destination,name);assert(target.startsWith(path.resolve(destination)+path.sep),'unsafe ZIP path');await fsp.mkdir(path.dirname(target),{recursive:true});await fsp.writeFile(target,bytes);}}
function sheets(file){const xml=parseZip(file).get('xl/workbook.xml')?.toString('utf8')??'';return[...xml.matchAll(/<(?:[A-Za-z]+:)?sheet[^>]+name="([^"]+)"/gu)].map(match=>match[1]);}
function specColumns(file){const xml=parseZip(file).get('xl/worksheets/sheet1.xml')?.toString('utf8')??'';const columns=[...xml.matchAll(/\br="([A-Z]+)\d+"/gu)].map(match=>match[1]);assert(columns.length>0,'specification cells missing');assert(columns.every(column=>column==='A'||column==='B'),'specification has fields beyond column B');return 2;}
async function run(command,args,cwd){const started=Date.now();return await new Promise(resolve=>{const child=spawn(command,args,{cwd,windowsHide:true});let stdout='',stderr='',settled=false;child.stdout.on('data',chunk=>stdout+=chunk);child.stderr.on('data',chunk=>stderr+=chunk);child.on('error',error=>{if(!settled){settled=true;resolve({code:1,stdout,stderr:stderr+error.message,elapsed_ms:Date.now()-started});}});child.on('exit',code=>{if(!settled){settled=true;resolve({code:code??1,stdout,stderr,elapsed_ms:Date.now()-started});}});});}
function treeDigest(root){const lines=[];function visit(current,prefix=''){for(const entry of fs.readdirSync(current,{withFileTypes:true}).toSorted((a,b)=>a.name.localeCompare(b.name))){const relative=prefix?prefix+'/'+entry.name:entry.name,full=path.join(current,entry.name);if(entry.isDirectory())visit(full,relative);else if(!relative.startsWith('output/'))lines.push(relative+'\0'+shaFile(full));}}visit(root);return sha(Buffer.from(lines.join('\n')));}
function parseCsv(text){const lines=text.trim().split(/\r?\n/u),headers=lines.shift().split(',');return lines.map(line=>Object.fromEntries(line.split(',').map((value,index)=>[headers[index],value])));}
function semanticReports(root){const reportRoot=path.join(root,'output','reports');return{breaking:parseCsv(fs.readFileSync(path.join(reportRoot,'breaking_changes.csv'),'utf8')).toSorted((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b))),deprecation:parseCsv(fs.readFileSync(path.join(reportRoot,'deprecation_windows.csv'),'utf8')).toSorted((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b))),sdk:parseCsv(fs.readFileSync(path.join(reportRoot,'sdk_impact_matrix.csv'),'utf8')).toSorted((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b))),advisory:JSON.parse(fs.readFileSync(path.join(reportRoot,'release_advisory.json'),'utf8')),consistency:JSON.parse(fs.readFileSync(path.join(reportRoot,'report_consistency.json'),'utf8'))};}
async function prepare(label,mutate){const runRoot=path.join(os.tmpdir(),label);await fsp.rm(runRoot,{recursive:true,force:true});await fsp.mkdir(runRoot,{recursive:true});await extract(path.join(artifactRoot,'输入数据包.zip'),runRoot);const refRoot=path.join(runRoot,'reference');await extract(path.join(artifactRoot,'reference.zip'),refRoot);await fsp.mkdir(path.join(runRoot,'output'),{recursive:true});await fsp.copyFile(path.join(refRoot,'output','check_api_compat.mjs'),path.join(runRoot,'output','check_api_compat.mjs'));if(mutate)await mutate(runRoot);return{runRoot,refRoot};}
async function execute(runRoot){return await run(process.execPath,['output/check_api_compat.mjs','.'],runRoot);}
function reportDigest(root){return sha(Buffer.from(JSON.stringify(semanticReports(root))));}

await fsp.rm(evidenceRoot,{recursive:true,force:true});await fsp.mkdir(evidenceRoot,{recursive:true});
assert(process.platform==='win32'&&process.env.GITHUB_ACTIONS==='true','Windows hosted runner required');
for(const[name,expected]of Object.entries(attachments))assert(shaFile(path.join(artifactRoot,name))===expected,name+' checksum mismatch');
for(const[name,expected]of Object.entries(taskHashes))assert(shaFile(path.join(repoRoot,'task',name))===expected,name+' task checksum mismatch');
const input=parseZip(path.join(artifactRoot,'输入数据包.zip')),reference=parseZip(path.join(artifactRoot,'reference.zip'));
assert(JSON.stringify([...reference.keys()].sort())===JSON.stringify(deliveryMembers),'Reference member list mismatch');
const platform=[...input,...reference].filter(([name,bytes])=>(bytes[0]===0x7f&&bytes.subarray(1,4).toString()==='ELF')||/\.(?:sh|bash|so)$/iu.test(name));assert(platform.length===0,'platform-specific member found');
assert(JSON.stringify(sheets(path.join(artifactRoot,'关键标准答案.xlsx')))===JSON.stringify(['交付物答案清单','固定字段答案','固定集合答案','固定数值答案','允许变体答案']),'answer sheet names mismatch');
assert(JSON.stringify(sheets(path.join(artifactRoot,'任务规格转化.xlsx')))===JSON.stringify(['任务规格转化']),'specification sheet mismatch');assert(specColumns(path.join(artifactRoot,'任务规格转化.xlsx'))===2,'specification column count mismatch');
const cleanRuns=[];for(const label of ['Q10543 clean gateway release','Q10543 中文 空格 网关发布']){const prepared=await prepare(label),before=treeDigest(prepared.runRoot),result=await execute(prepared.runRoot),after=treeDigest(prepared.runRoot);assert(result.code===0,'clean run failed '+result.stdout+' '+result.stderr);assert(before===after,'input changed during clean run');const actual=reportDigest(prepared.runRoot),expected=reportDigest(prepared.refRoot);assert(actual===expected,'reports differ from Reference');cleanRuns.push({directory_label:label,exit_code:result.code,input_digest_before:before,input_digest_after:after,semantic_digest:actual,elapsed_ms:result.elapsed_ms});}assert(cleanRuns[0].semantic_digest===cleanRuns[1].semantic_digest,'clean run results differ');
const changed=await prepare('Q10543 changed deprecation policy',async root=>{const file=path.join(root,'compat_policy.json'),policy=JSON.parse(await fsp.readFile(file,'utf8'));policy.min_deprecation_days=60;await fsp.writeFile(file,JSON.stringify(policy,null,2)+'\n');});let result=await execute(changed.runRoot);assert(result.code===0,'changed policy failed '+result.stderr);const changedWindow=parseCsv(await fsp.readFile(path.join(changed.runRoot,'output','reports','deprecation_windows.csv'),'utf8')).find(row=>row.operation_id==='validateCoupon');assert(changedWindow?.policy_result==='pass','changed policy did not affect deprecation result');const changedAdvisory=JSON.parse(await fsp.readFile(path.join(changed.runRoot,'output','reports','release_advisory.json'),'utf8'));assert(changedAdvisory.deprecation_policy_failures===1,'changed policy did not affect advisory');
const invalid=await prepare('Q10543 missing candidate contract',async root=>{await fsp.rename(path.join(root,'openapi','candidate.json'),path.join(root,'openapi','candidate.json.missing'));});result=await execute(invalid.runRoot);assert(result.code!==0,'missing candidate contract accepted');assert(!fs.existsSync(path.join(invalid.runRoot,'output','reports')),'invalid input left reports');
const evidence={schema_version:1,task_asset_id:'api_gateway_openapi_sdk_impact',result:'PASS',generated_at_utc:new Date().toISOString(),git_commit_sha:process.env.GITHUB_SHA,workflow_run_id:process.env.GITHUB_RUN_ID,runner:{os:process.env.RUNNER_OS,arch:process.env.RUNNER_ARCH,image_os:process.env.ImageOS,image_version:process.env.ImageVersion,node:process.version,powershell_hosted_workflow:true},software:{main:'Node.js',version:process.version,executed:true},attachment_sha256:attachments,task_text_sha256:taskHashes,workbook_checks:{answer_sheet_names:sheets(path.join(artifactRoot,'关键标准答案.xlsx')),specification_sheet_names:['任务规格转化'],task_spec_column_count:2},platform_audit:{platform_specific_members:platform,linux_executables_executed:false,no_wsl_required:true,no_linux_container_required:true,no_posix_shell_required:true,cross_platform_paths:true},clean_runs:cleanRuns,reference_match:true,positive_mutation:{changed_rule:'min_deprecation_days 180 to 60',exit_code:0,expected_operation:'validateCoupon',result_changed:true},invalid_input:{changed_rule:'openapi candidate missing',exit_code:result.code,no_reports_output:true},network:{installation:'GitHub setup-node',formal_run:'local files only'}};
await fsp.writeFile(path.join(evidenceRoot,'windows-verification.json'),JSON.stringify(evidence,null,2)+'\n');console.log(JSON.stringify(evidence,null,2));
